version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 80s docker-entrypoint.sh
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    env_file:
      - .env
    command:
      - 'npm'
      - 'run'
      - 'dev'
    networks:
      - app_network
    ports:
      - "3333:3333"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${PASS_DB}
      POSTGRES_DB: people
      POSTGRES_USER: ${USER_DB}
    env_file:
      - .env
    volumes:
      - ./database/entrypoint.sh:/docker-entrypoint-initdb.d/10_postgis.sh
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
