apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployk8s-hpa
  namespace: deployk8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: deployk8s-server
    kind: Deployment
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 25